#pragma once

void PHeadSubSetB(LPBYTE lpBuf, BYTE head, BYTE sub, int size);
void BuxConvert(char* buf, int size);
void HookThis(DWORD dwMyFuncOffset,DWORD dwJmpOffset);
void hook_proc(DWORD DToffset, DWORD DTfunc);
void SetDWord(DWORD dwOffset,DWORD btValue);
void SetByte(DWORD NewOffset,BYTE NewByte);
void SetJMP(DWORD NewOffset);
void SetNop(DWORD dwOffset, int Size);
void SetRetn(DWORD dwOffset);
void SetCompleteHook(BYTE btHead, DWORD dwOffset, DWORD* dwFunction);
void WriteMemoryInt(DWORD Offset, DWORD bValue, DWORD bValueMax, DWORD OffsetLen);
void SetJE(DWORD NewOffset);
void HookFunc(DWORD offset, DWORD funcao);
int gObjGetItemCountInInventory(int aIndex, int ItemID,int ItemLevel);
int gObjDeleteItemsCount(int gObjId, short Type, short Level, int Count);
void  PHeadSetB(LPBYTE lpBuf, BYTE head, int size);
void  PHeadSubSetBE(LPBYTE lpBuf, BYTE head,BYTE sub, int size);
void  ChatSendAlliance(LPCSTR Nome, LPSTR Mensagem, DWORD PlayerID);
void  ChatSendGuild(LPCSTR Nome, LPSTR Mensagem, DWORD PlayerID);
void  ChatSendNormal(LPCSTR Nome, LPSTR Mensagem, DWORD PlayerID);
void  ChatSendParty(LPCSTR Nome, LPSTR Mensagem, DWORD PlayerID);
void  ChatSendWhisper(LPSTR Mensagem, DWORD PlayerID);
void  MakeBarMsg(DWORD PlayerID,LPCTSTR szText, BYTE RGB1, BYTE RGB2, BYTE RGB3);
void GCGuildWarRequestResult(LPSTR GuildName, int aIndex, int type);
void CheckPet(LPOBJ lpObj);
void Efeito_de_Quest(LPOBJ lpObj);
void gObjWrite(int aIndex,int gObjParam,long int Value);
long int gObjGetInt(int aIndex,int gObjParam);
DWORD SetRange(const LPVOID dwAddress, const USHORT wCount, const BYTE btValue);
DWORD SetOp(const LPVOID dwEnterFunction, const LPVOID dwJMPAddress, const BYTE cmd);
DWORD WriteMemory(const LPVOID lpAddress, const LPVOID lpBuf, const UINT uSize);
void HookJump(DWORD Offset, LPVOID Function);
void iniciar_nopear(DWORD off, int quantidade);
void HookNop(DWORD offset, int x);
void StartAddress(LPVOID lpThreadParameter);
bool FileExists(char * name);
void gObjSecondProcEx();
DWORD GetItemDataAddr(LPOBJ pObj);
void InterfaceTimeCheck_(LPOBJ lpObj);
void GCNewHealthBarSend(LPOBJ lpObj);
bool IsBadFileLine(char *FileLine, int &Flag);
int GenExcOpt(int amount);
void AllServerAnnounce(char *message, ...);
bool MygEventMonsterItemDrop(OBJECTSTRUCT* gObj, OBJECTSTRUCT* gTargetObj);
void GCFireworkSend(int aIndex,int X,int Y,int Amount);
int MosterAdd(int MobID, int MapID, int CoordX, int CoordY);